# Generated by Django 3.2.4 on 2021-08-11 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_login', models.TextField(unique=True, verbose_name='Логин пользователя в Steam')),
                ('steam_password', models.TextField(verbose_name='Пароль от Steam')),
                ('steam_name', models.TextField(verbose_name='Имя пользователя в Steam')),
                ('steam_link', models.TextField(verbose_name='Ссылка на профиль')),
                ('email', models.TextField(verbose_name='Почта к которой привязан аккаунт')),
                ('email_password', models.TextField(verbose_name='Пароль от почты')),
                ('type', models.TextField(verbose_name='Тип аккаунта')),
                ('status', models.BooleanField(verbose_name='Статус аккаунта')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.TextField(verbose_name='Прокси')),
                ('country', models.TextField(verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Прокси',
                'verbose_name_plural': 'Прокси',
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True, verbose_name='Код покупки')),
                ('game_link', models.TextField(verbose_name='Ссылка на игру')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.account', verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Ключ',
                'verbose_name_plural': 'Ключи',
            },
        ),
    ]
