# Generated by Django 3.2.4 on 2021-08-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210812_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='app_code',
            field=models.PositiveIntegerField(verbose_name='Код игры в стиме'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.TextField(verbose_name='Название игры'),
        ),
    ]
