# Generated by Django 3.2.4 on 2021-08-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210812_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.TextField(default='Arg', verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='country',
            field=models.TextField(default='Arg', verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
