# Generated by Django 3.2.4 on 2021-08-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210814_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True, verbose_name='Код')),
                ('value', models.PositiveIntegerField(verbose_name='Сумма')),
                ('country', models.TextField(verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Код попелнения',
                'verbose_name_plural': 'Коды попелнения',
            },
        ),
        migrations.DeleteModel(
            name='Proxy',
        ),
        migrations.RemoveField(
            model_name='account',
            name='steam_link',
        ),
        migrations.RemoveField(
            model_name='account',
            name='steam_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
    ]
