# Generated by Django 3.2.4 on 2021-08-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_steamcode_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamcode',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
